#:schema node_modules/wrangler/config-schema.json
name = "dungen-game2"
main = "functions/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"


[[kv_namespaces]]
binding = "GAME_STATE"
id = "e5cb121461664c04b66b64bcea54685f"

[site]
bucket = "./public"

pages_build_output_dir = "./public"
